-- MySQL Script generated by MySQL Workbench
-- lun 30 dic 2019 13:49:06 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema upocasa
-- -----------------------------------------------------
-- IMPORTANTE, poner en el SQL exportado:
-- DEFAULT COLLATE 'utf8mb4_spanish_ci'
-- UTF8 -> UTF8MB4; spanish_ci (Moderno, CH y LL NO son letras)
DROP SCHEMA IF EXISTS `upocasa` ;

-- -----------------------------------------------------
-- Schema upocasa
--
-- IMPORTANTE, poner en el SQL exportado:
-- DEFAULT COLLATE 'utf8mb4_spanish_ci'
-- UTF8 -> UTF8MB4; spanish_ci (Moderno, CH y LL NO son letras)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upocasa` 
DEFAULT CHARACTER SET utf8mb4 
DEFAULT COLLATE 'utf8mb4_spanish_ci';
USE `upocasa` ;

-- -----------------------------------------------------
-- Table `upocasa`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `nick` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `clave` VARCHAR(120) NOT NULL,
  `alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`tiposAnuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`tiposAnuncio` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`tiposAnuncio` (
  `idTipoAnuncio` INT NOT NULL AUTO_INCREMENT,
  `tipoAnuncio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoAnuncio`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipoAnuncio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tipos de Anuncio\n';


-- -----------------------------------------------------
-- Table `upocasa`.`tiposVivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`tiposVivienda` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`tiposVivienda` (
  `idtipoVivienda` INT NOT NULL AUTO_INCREMENT,
  `tipoVivienda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoVivienda`),
  UNIQUE INDEX `tipoVivienda_UNIQUE` (`tipoVivienda` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tipos de Vivienda';


-- -----------------------------------------------------
-- Table `upocasa`.`anuncios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`anuncios` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`anuncios` (
  `idAnuncio` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idTipoAnuncio` INT NOT NULL,
  `idTipoVivienda` INT NOT NULL,
  `precio` DECIMAL NOT NULL,
  `superficie` DECIMAL NOT NULL,
  `direccion` VARCHAR(120) NOT NULL,
  `codPostal` SMALLINT(2) UNSIGNED NOT NULL,
  `numHabitaciones` TINYINT(2) NULL,
  `numAseos` TINYINT(2) NULL,
  `consumo` CHAR(1) NULL,
  `emisiones` CHAR(1) NULL,
  `comentarios` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idAnuncio`),
  INDEX `fk_anuncios_usuarios_idx` (`idUsuario` ASC),
  INDEX `fk_anuncios_tiposAnuncio_idx` (`idTipoAnuncio` ASC),
  INDEX `fk_anuncios_tiposVivienda_idx` (`idTipoVivienda` ASC),
  CONSTRAINT `fk_anuncios_usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_tiposAnuncio`
    FOREIGN KEY (`idTipoAnuncio`)
    REFERENCES `upocasa`.`tiposAnuncio` (`idTipoAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_tiposVivienda`
    FOREIGN KEY (`idTipoVivienda`)
    REFERENCES `upocasa`.`tiposVivienda` (`idtipoVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Anuncios por usuario [∞ ← 1]\n';


-- -----------------------------------------------------
-- Table `upocasa`.`fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`fotos` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`fotos` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `idAnuncio` INT NULL,
  `urlFoto1` VARCHAR(45) NULL,
  `urlFoto2` VARCHAR(45) NULL,
  `urlFoto3` VARCHAR(45) NULL,
  `urlFoto4` VARCHAR(45) NULL,
  `urlFoto5` VARCHAR(45) NULL,
  INDEX `fk_fotos_anuncios_idx` (`idAnuncio` ASC),
  PRIMARY KEY (`idFoto`),
  CONSTRAINT `fk_fotos_anuncios`
    FOREIGN KEY (`idAnuncio`)
    REFERENCES `upocasa`.`anuncios` (`idAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`mensajes` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`mensajes` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `idUsuOrigen` INT NOT NULL,
  `idUsuDestino` INT NOT NULL,
  `mensaje` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_mensajes_usuarios_idx` (`idUsuOrigen` ASC),
  INDEX `fk_mensajes_usuarios2_idx` (`idUsuDestino` ASC),
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`idUsuOrigen`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`idUsuDestino`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`extras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`extras` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`extras` (
  `idExtra` INT NOT NULL AUTO_INCREMENT,
  `extra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExtra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`anuncios_extras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`anuncios_extras` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`anuncios_extras` (
  `idAnuncio` INT NOT NULL,
  `idExtra` INT NOT NULL,
  PRIMARY KEY (`idAnuncio`, `idExtra`),
  INDEX `fk_anuncios_extras_extras_idx` (`idExtra` ASC),
  CONSTRAINT `fk_anuncios_extras_anuncios`
    FOREIGN KEY (`idAnuncio`)
    REFERENCES `upocasa`.`anuncios` (`idAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_extras_extras`
    FOREIGN KEY (`idExtra`)
    REFERENCES `upocasa`.`extras` (`idExtra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- INSERT
-- -----------------------------------------------------

-- Tipos de Anuncio
INSERT INTO `tiposAnuncio` (`idTipoAnuncio`, `tipoAnuncio`) VALUES
(1, 'Vendo'),
(2, 'Alquilo'),
(3, 'Comparto'),
(4, 'Vacacional');

-- Tipos de Vivienda
INSERT INTO `tiposVivienda` (`idtipoVivienda`, `tipoVivienda`) VALUES
(1, 'Vivienda'),
(2, 'Garaje'),
(3, 'Terreno'),
(4, 'Local Comercial'),
(5, 'Oficina'),
(6, 'Trastero');

-- Extras
INSERT INTO `extras` (`idExtra`, `extra`) VALUES
(1, 'Garaje Privado'),
(2, 'Trastero'),
(3, 'Ascensor'),
(4, 'Parking Comunitario'),
(5, 'Servicio de Portería'),
(6, 'Videoportero'),
(7, 'Aire acondicionado'),
(8, 'Armarios'),
(9, 'Calefacción'),
(10, 'Parquet'),
(11, 'Cocina Office'),
(12, 'Suite con baño'),
(13, 'Amueblado'),
(14, 'Electrodomésticos'),
(15, 'Horno'),
(16, 'Lavadora'),
(17, 'Microondas'),
(18, 'Nevera'),
(19, 'TV'),
(20, 'Internet'),
(21, 'Puerta Blindada'),
(22, 'Lavadero'),
(23, 'No Amueblado'),
(24, 'Jardín Privado'),
(25, 'Terraza'),
(26, 'Zona Comunitaria'),
(27, 'Patio'),
(28, 'Piscina'),
(29, 'Balcón'),
(30, 'Zona Deportiva'),
(31, 'Zona Infantil'),
(32, 'Piscina Comunitaria');

-- Usuarios
INSERT INTO `usuarios` 
(`idUsuario`, `nombre`, `nick`, `correo`, `clave`, `alta`) 
VALUES
(1, 'Alejandro', 'alex', 'alejandrodh570@gmail.com', '$2y$10$MyxsqyP/3QIwrDbQcY5Y4erf36G0d/0ki9y4cOlRhFKsNZVlEg/W6', '2019-12-30 17:56:27'),
(2, 'Iván', 'ivan', 'ivanrguez1@yahoo.es', '$2y$10$WemNiU3zyP1qY.lN8VOVeOy9Xrsv6aYHXaFfb69xC5w7rjqvriUeK', '2019-12-30 17:57:13');

-- Anuncios
INSERT INTO `anuncios` 
(`idAnuncio`, `idUsuario`, `idTipoAnuncio`, `idTipoVivienda`, 
`precio`, `superficie`, `direccion`, `codPostal`, `numHabitaciones`, 
`numAseos`, `consumo`, `emisiones`, `comentarios`) 
VALUES
(1, 2, 1, 2, '23000', '30', 'Paris, 29', 41089, 0, 0, 'A', 'A', 'Parking en Montequinto'),
(2, 2, 1, 2, '15000', '100', 'Paris, 14', 41089, 0, 0, 'A', 'A', 'Parking en Montequinto'),
(3, 2, 1, 1, '230000', '110', 'Paris, 29', 41089, 3, 2, 'A', 'A', 'Piso en Montequinto Calle ParÃ­s'),
(4, 2, 1, 1, '230000', '110', 'Paris, 29', 41089, 3, 2, 'A', 'A', 'Piso en Montequinto Calle ParÃ­s'),
(5, 2, 1, 1, '230000', '110', 'Paris, 29', 41089, 3, 2, 'A', 'A', 'Piso en Montequinto Calle ParÃ­s'),
(6, 2, 1, 1, '250000', '120', 'Paris, 23', 41089, 3, 2, 'A', 'A', 'Prueba'),
(7, 2, 1, 1, '900000', '175', 'San Bernardo', 41012, 5, 4, 'A', 'A', 'Prueba Final');

-- Anuncios-extras
INSERT INTO `anuncios_extras` (`idAnuncio`, `idExtra`) VALUES
(4, 1),(5, 1),(7, 1),(7, 3),
(4, 7),(5, 7),(7, 7),(7, 9),
(7, 10),(4, 24),(5, 24),(7, 24),
(7, 26),(7, 27);

-- Fotos
INSERT INTO `fotos` (`idFoto`, `idAnuncio`, `urlFoto1`, `urlFoto2`, `urlFoto3`, `urlFoto4`, `urlFoto5`) VALUES
(2, 6, 'assets/img/ads/destacado2.jpg', NULL, NULL, NULL, NULL),
(3, 7, 'assets/img/ads/destacado3.jpg', NULL, NULL, NULL, NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
