-- MySQL Script generated by MySQL Workbench
-- lun 30 dic 2019 12:39:59 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema upocasa
-- -----------------------------------------------------
-- IMPORTANTE, poner en el SQL exportado:
-- DEFAULT COLLATE 'utf8mb4_spanish_ci'
-- UTF8 -> UTF8MB4; spanish_ci (Moderno, CH y LL NO son letras)
DROP SCHEMA IF EXISTS `upocasa` ;

-- -----------------------------------------------------
-- Schema upocasa
--
-- IMPORTANTE, poner en el SQL exportado:
-- DEFAULT COLLATE 'utf8mb4_spanish_ci'
-- UTF8 -> UTF8MB4; spanish_ci (Moderno, CH y LL NO son letras)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `upocasa` 
DEFAULT CHARACTER SET utf8mb4 
DEFAULT COLLATE 'utf8mb4_spanish_ci';
USE `upocasa` ;

-- -----------------------------------------------------
-- Table `upocasa`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`usuarios` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `clave` VARCHAR(120) NOT NULL,
  `alta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`tiposAnuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`tiposAnuncio` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`tiposAnuncio` (
  `idTipoAnuncio` INT NOT NULL,
  `tipoAnuncio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoAnuncio`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipoAnuncio` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tipos de Anuncio\n';


-- -----------------------------------------------------
-- Table `upocasa`.`tiposVivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`tiposVivienda` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`tiposVivienda` (
  `idtipoVivienda` INT NOT NULL,
  `tipoVivienda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoVivienda`),
  UNIQUE INDEX `tipoVivienda_UNIQUE` (`tipoVivienda` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Tipos de Vivienda';


-- -----------------------------------------------------
-- Table `upocasa`.`anuncios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`anuncios` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`anuncios` (
  `idAnuncio` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idTipoAnuncio` INT NOT NULL,
  `idTipoVivienda` VARCHAR(45) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `superficie` DECIMAL NOT NULL,
  `direccion` VARCHAR(120) NOT NULL,
  `codPostal` TINYINT(5) NOT NULL,
  `numHabitaciones` TINYINT(2) NOT NULL,
  `numAseos` TINYINT(2) NOT NULL,
  `consumo` CHAR(1) NULL,
  `emisiones` CHAR(1) NULL,
  `comentarios` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idAnuncio`),
  UNIQUE INDEX `idAnuncio_UNIQUE` (`idAnuncio` ASC),
  INDEX `fk_anuncios_usuarios_idx` (`idUsuario` ASC),
  INDEX `fk_anuncios_tiposAnuncio_idx` (`idTipoAnuncio` ASC),
  INDEX `fk_anuncios_tiposVivienda_idx` (`idTipoVivienda` ASC),
  CONSTRAINT `fk_anuncios_usuarios`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_tiposAnuncio`
    FOREIGN KEY (`idTipoAnuncio`)
    REFERENCES `upocasa`.`tiposAnuncio` (`idTipoAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncios_tiposVivienda`
    FOREIGN KEY (`idTipoVivienda`)
    REFERENCES `upocasa`.`tiposVivienda` (`tipoVivienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Anuncios por usuario [∞ ← 1]\n';


-- -----------------------------------------------------
-- Table `upocasa`.`fotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`fotos` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`fotos` (
  `idFoto` INT NOT NULL,
  `idAnuncio` INT NULL,
  `urlFoto1` VARCHAR(45) NULL,
  `urlFoto2` VARCHAR(45) NULL,
  `urlFoto3` VARCHAR(45) NULL,
  `urlFoto4` VARCHAR(45) NULL,
  `urlFoto5` VARCHAR(45) NULL,
  INDEX `fk_fotos_anuncios_idx` (`idAnuncio` ASC),
  PRIMARY KEY (`idFoto`),
  CONSTRAINT `fk_fotos_anuncios`
    FOREIGN KEY (`idAnuncio`)
    REFERENCES `upocasa`.`anuncios` (`idAnuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `upocasa`.`mensajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `upocasa`.`mensajes` ;

CREATE TABLE IF NOT EXISTS `upocasa`.`mensajes` (
  `idMensajes` INT NOT NULL,
  `idUsuOrigen` INT NOT NULL,
  `idUsuDestino` INT NOT NULL,
  `mensaje` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idMensajes`),
  INDEX `fk_mensajes_usuarios_idx` (`idUsuOrigen` ASC),
  INDEX `fk_mensajes_usuarios2_idx` (`idUsuDestino` ASC),
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`idUsuOrigen`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`idUsuDestino`)
    REFERENCES `upocasa`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
